### ISSUE TITLE
When you add a new domain you have to reload the page to add another

### ISSUE THREAD

**Issue by jchoudha** [jawr/whois-bi#5]
When you add a new domain it replaces the 'Enter Domain to start monitoring' entry box with 'Added. Please wait while we prepare things for you.'.

To add another domain you then have to reload the webpage, or click the Dashboard link.

It would be good if the 'Enter Domain to start monitoring' would still be available on the page so you can add another domain without of having to navigate back to the page.

**Comment by jawr** [comment]
There was a timeout of 10 seconds, but thats too long. Changed it to be a little bit more user friendly in https://github.com/jawr/whois-bi/pull/9
